name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'exp/1.9'

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[publish]') || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-24.04
    steps:
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - name: Upload to Maven
        run: ./gradlew publish --stacktrace
        env:
          CLOUDSMITH_MAVEN_TOKEN: ${{ secrets.CLOUDSMITH_MAVEN_TOKEN }}
